name: Update Velog Posts
  
on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'  # 매일 자정에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run new script
      run: |
        python scripts/velog_post_parser.py
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Commit changes
      run: |
       git config --global user.name 'JuYoungJun'
       git config --global user.email 'kaks162@gmail.com'
       git pull origin main  # 원격 저장소의 변경사항을 로컬로 가져옴
       git add README.md
       git commit -m 'Update README.md with new Velog posts'
       git push origin main  # 변경사항을 다시 원격 저장소로 push
      env:
       GH_PAT: ${{ secrets.GH_PAT }}
