name: Update Velog Posts
  
on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'  # 매일 자정에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
       git config --global user.name 'JuYoungJun'
       git config --global user.email 'kaks162@gmail.com'
       git push https://${GH_PAT}@github.com/rimgosu/velog.git

       - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 예시로 3.9로 설정

       - name: Install dependencies
        run: |
        pip install feedparser gitpython

       - name: Run script
        run: python scripts/update_velog.py
