name: Update Velog Posts
  
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run new script
      run: |
        python scripts/velog_post_parser.py
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Run update_velog.py
      run: |
        python scripts/update_velog.py
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Resolve merge conflicts in README.md
      run: |
        git config --global user.email "kaks162@gmail.com"
        git config --global user.name "JuYoungJun"
        git checkout --theirs README.md
        git add README.md
        git diff-index --quiet HEAD || git commit -m 'Resolve merge conflict in README.md'
      continue-on-error: true

    - name: Push changes to main branch
      run: git push origin main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
